### ISSUE TITLE
Skip Tools option, skips [toolsblack]

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#10]
Tools/toolsblack is not an invisible brush material, but is inherently effected by the Skip tools option.
Obviously this tool is used rather decoratively, and lacking it causes expected issues like this: https://i.imgur.com/RC1Jo10.png

-Lower importance: toolsblack needs also have zero specular, along with overlays/black_gradient

**Comment by matty45** [comment]
make sure to incorporate these as well: ![](https://i.imgur.com/KQfziIE.png)

**Comment by lasa01** [comment]
Should be fixed now.
