### ISSUE TITLE
Import all classes

### ISSUE THREAD

**Issue by DFliyerz** [lasa01/io_import_vmf#106]
I'm trying to import maps from Infra but there's multiple things that don't import correctly, such as infodecals and some of Infra's custom classes. While I can place these manually, it would be nice if the importer would place something at each location even if it's just an empty object.

**Comment by lasa01** [comment]
This is fixed in Plumber 1.0.0 beta versions, you can try the latest version [here](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3).
