### ISSUE TITLE
Wrong face orientations on some displacements

### ISSUE THREAD

**Issue by matty45** [lasa01/io_import_vmf#12]
While messing around with the importer, i discovered a bug when using a certain vmf.

[VMF Download
](https://www.dropbox.com/s/cd2qw4ros33ihx1/gm_fork_source.zip?dl=1)

I found that a part of the imported vmf seems to have invisible textures.

VMF in hammer: ![](https://i.imgur.com/ja9tg3b.jpg)

VMF in Blender: ![](https://i.imgur.com/C38skux.jpg)

Untextured view : ![](https://i.imgur.com/QaRbqAv.jpg)

Bug found using latest build of the plugin: 771a97576cb17fa7951e70972b1398cc209438b2

**Comment by lasa01** [comment]
It seems that the face orientation of the mesh is wrong.

I assume you have enabled backface culling, in which case the material would appear invisible from one side. Can you check if the material is visible from the other side?

Also found another issue with importing some of the materials there, but that is probably unrelated.

**Comment by matty45** [comment]
will check
btw did not tick allow backface culling in import settings.
Yup, material is visible on the other side.

**Comment by lasa01** [comment]
Looks like there is a bug in the backface culling setting too, it is always used regardless of what the user selects.

I will see if I can find the problem with the incorrect face orientation.

**Comment by lasa01** [comment]
This should be fixed now.
