### ISSUE TITLE
Could not detect installed games | Plumber 1.0.0

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#120]
"[Plumber] [ERROR] Could not detect installed games: error deserializing appmanifest: unexpected eof at line 1, column 1"

All I do is launch Blender with the plugin enabled and/or select to Redetect installed games.
Given this is all the error I get within the logs, I'm not sure what manifest file its trying to use.

Windows 10
Blender 3.2.0
Plumber Release 1.0.0

**Comment by lasa01** [comment]
Check out the latest release, you should get a more helpful error.
