### ISSUE TITLE
"Filter Supported" hiding supported files | Plumber 1.0.0

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#121]
Filter Supported checkbox within the import browser, filters away ALL files including supported VMFs.

Have no automatic detected directories. 
Added my own game definition.
Set my game definition search path to Team Fortress 2's root folder.
Import>Plumber>Browse>TeamFortress2.
Navigate to any folder with a valid VMF with "Filter Supported" enabled.

I expected it to filter away BSPs, and still include VMFs.

https://i.imgur.com/qzbcu4p.png

Windows 10
Blender 3.2.0
Plumber Release 1.0.0
Team Fortress 2

**Comment by lasa01** [comment]
Should be fixed in latest release.
