### ISSUE TITLE
The game file browser cannot read CS:S files | Plumber

### ISSUE THREAD

**Issue by JokanJan** [lasa01/io_import_vmf#125]
**Describe the bug**
The plugin reports an error when using the Game File Browser to view CS:S files. Even when switching to English in Steam's game properties, it still lacks the cstrike_english.vpk file mentioned in its error.

**Logs**
```
[Plumber] [WARN] opening filesystem: vpk file `J:\SteamLibrary\steamapps\common\Counter-Strike Source\cstrike/cstrike_english.vpk` not found
Traceback (most recent call last):
  File "C:\Users\jian8\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\plumber\tools.py", line 193, in invoke
    GameFileBrowser.browser = game.get_file_system().browse()
OSError: error reading `J:\SteamLibrary\steamapps\common\Counter-Strike Source\cstrike/cstrike_english.vpk`: reading vpk failed: io error: 系统找不到指定的文件。 (os error 2)
```

**Screenshots**
![Snipaste_2022-06-12_09-42-06](https://user-images.githubusercontent.com/46306699/173210641-c03d7212-1db5-43e8-a99e-eb9c9b88fd02.png)

**Details (please complete the following information):**
 - OS: Win10
 - Blender Version: 3.2.0
 - Addon Version: Plumber 1.0.0-beta1
 - Related Game: Counter-Strike Source

**Comment by lasa01** [comment]
The gameinfo.txt probably contains this file even though it doesn't exist.
I'll change it to just warn on missing files instead of throwing an
exception.

**Comment by lasa01** [comment]
Should be fixed in latest release.
