### ISSUE TITLE
Game file browser interface optimization | Plumber

### ISSUE THREAD

**Issue by JokanJan** [lasa01/io_import_vmf#126]
**Can the game file browser be presented in a sidebar?**

The game file browser is a pleasant surprise, but the current pop-up presentation is a bit inconvenient in practice.
First of all, you can't manipulate the view when the browser is open, such as rotating the view in 3d view or viewing the outline view. Secondly, it is easy to close the browser by accidentally touching the area outside the pop-up window. And the menu path to open the browser is too long (although this can be solved by quick favorites), which makes it very inconvenient to reopen the browser and return to the previous position, which requires a lot of operations.

If you use the sidebar, you can avoid the incident of closing the browser by mistake, and make the browser more convenient and efficient to use.

**For example:**
![Snipaste_2022-06-12_10-54-24](https://user-images.githubusercontent.com/46306699/173212633-346aa681-5b1f-4373-a01c-434c52679b89.png)

**Comment by lasa01** [comment]
Good suggestion, could also add an option to disable it from the sidebar to
the preferences in case people don't want to clutter the sidebar.

**Comment by lasa01** [comment]
Implemented the initial suggestions. Displaying the import settings directly on the file browser can unfortunately not be done easily.
