### ISSUE TITLE
Addon does not properly support/import 4WayBlend materials | Plumber

### ISSUE THREAD

**Issue by Carkidd** [lasa01/io_import_vmf#128]
Plumber will fail to properly import Lightmapped_4WayBlend materials. These are only found in CS:GO and Black Mesa Source. It will currently only display one of the blend textures.

https://developer.valvesoftware.com/wiki/Lightmapped_4WayBlend

This is how a 4WayBlend looks when imported- 
![issue plumber](https://user-images.githubusercontent.com/7998107/174988078-cf3b621f-1c0c-4127-94fe-e9cff4826385.png)

And this is how the terrain looks in-game-
![issue ingame](https://user-images.githubusercontent.com/7998107/174987944-ffd70d76-d0d9-4d09-86f9-c256eb4eb00b.jpg)

**Comment by lasa01** [comment]
The blending calculations seem to be implemented [here](https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/materialsystem/stdshaders/lightmapped_4wayblend_ps20b.fxc#L354-L468), would need to figure out how to convert that to blender nodes.

Also a minimal example vmf file with a single 4WayBlended displacement would help with testing in case anyone wants to help.

**Comment by Carkidd** [comment]
Here is two examples from Black Mesa. One is filled out per the Source wiki, and the other appears to be auto-generated with Wall Worm Pro. Some values are missing from both- the Wall Worm Pro version has a different surfaceprop type per blended surface (not useful in Blender) and the Source Wiki version has evnmap, basealphaenvmapmask, envmaptint and color2 defined.


[blend_4way_bnc_rock_srcwiki.txt](https://github.com/lasa01/io_import_vmf/files/9077828/blend_4way_bnc_rock_srcwiki.txt)
[blend_4way_st_b_rock_wallworm.txt](https://github.com/lasa01/io_import_vmf/files/9077829/blend_4way_st_b_rock_wallworm.txt)

**Comment by lasa01** [comment]
Implemented in the latest beta release.
