### ISSUE TITLE
Models imported with the file browser or MDL import are 100x scale | Plumber

### ISSUE THREAD

**Issue by Carkidd** [lasa01/io_import_vmf#129]
Models when imported with the file browser or MDL importer are imported at 100x scale. This was tested with Half Life 2 and Black Mesa models. This does not occur with the VMF importer, as it defaults to importing at .01 scale. 

Use the file browser or MDL importer to import a model. This can be done with either the 3D view tab or Import tab. 

This bug means an unnecessary scaling down of all imported models is required before they can be used. 

An imported model next to an imported map:
![image](https://user-images.githubusercontent.com/7998107/175760619-df942708-b347-420b-bb96-4433a2093401.png)

That same model scaled down by .01:
![image](https://user-images.githubusercontent.com/7998107/175760672-67c642e3-c802-4001-b89a-af5222a2c222.png)

**Comment by lasa01** [comment]
Actually the vmf is scaled down to 0.01 by default (there is a scale
setting), mdls are imported with 1.00 scale and don't have a separate
setting for adjusting the scale. Do you think it would be better to have
mdls too scaled down to 0.01 by default?

**Comment by Carkidd** [comment]
> Actually the vmf is scaled down to 0.01 by default (there is a scale setting), mdls are imported with 1.00 scale and don't have a separate setting for adjusting the scale. Do you think it would be better to have mdls too scaled down to 0.01 by default?

I JUST opened blender and noticed this! It would be best to have mdls scaled to .01 by default with the ability to change it, like VMFs.

**Comment by lasa01** [comment]
This is fixed in Plumber 1.0.0 beta versions, you can try the latest version [here](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3).
