### ISSUE TITLE
Add vtf import feature | Plumber

### ISSUE THREAD

**Issue by JokanJan** [lasa01/io_import_vmf#130]
**Since the vmt import feature is available, could you add a vtf import feature as well?**

In fact, I use this feature quite often, I use it to import csgo skin texture or mix multiple different game textures to make a new material in blender.

**Comment by lasa01** [comment]
This is fixed in Plumber 1.0.0 beta versions, you can try the latest version [here](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3).
