### ISSUE TITLE
bring back "Detect by game directory" button | Plumber

### ISSUE THREAD

**Issue by Fennecai** [lasa01/io_import_vmf#133]
**Is your feature request related to a problem? Please describe.**
in the new addon; the "detect from game dir" button has been replaced with a button that does that for every game you have all at once. this is problematic because I have some very special game configurations (due to a modding workflow I use when making p2 maps) and it gets a lot of them wrong or misses several because of that. its also annoying to manually have to add the ones it misses, due to them having lots of vpks and wildcard dirs etc... it would be nice to have the old button added back for a single game in addition to the new button; so that I can semi-manually select folders that the detection now completely misses.

**Is your feature request related to a specific game? Please specify.**
nope

**Describe the solution you'd like**
just add the old button back, maybe right under the new one.

**Additional context**
none

**Comment by lasa01** [comment]
I think a "detect from gameinfo.txt" would make more sense. Gameinfo.txt should have all the relevant directories, would this work for you?

**Comment by Fennecai** [comment]
yep that'd work fine. :)

**Comment by lasa01** [comment]
Implemented in the latest beta release.
