### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath' 

### ISSUE THREAD

**Issue by TheAwesome98-Real** [lasa01/io_import_vmf#134]
**Describe the bug**
When enabling the addon:
![image](https://user-images.githubusercontent.com/59254971/182128838-eb5723cb-e7dc-4e2c-9e7b-43942c0a93f9.png)
![image](https://user-images.githubusercontent.com/59254971/182128878-ccfd4bc8-c917-4ce8-ab19-fa365a4014bf.png)

**Expected behavior**
The addon to activate and me be able to import d1_trainstation_01_d.vmf

**To Reproduce**
1. Enable the addon on Linux

**Related files**
Upload an example of files that cause the issue [e.g. de_mirage_d.vmf].
N/A

**Logs**
![image](https://user-images.githubusercontent.com/59254971/182128838-eb5723cb-e7dc-4e2c-9e7b-43942c0a93f9.png)
![image](https://user-images.githubusercontent.com/59254971/182128878-ccfd4bc8-c917-4ce8-ab19-fa365a4014bf.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/59254971/182128838-eb5723cb-e7dc-4e2c-9e7b-43942c0a93f9.png)
![image](https://user-images.githubusercontent.com/59254971/182128878-ccfd4bc8-c917-4ce8-ab19-fa365a4014bf.png)

**Details (please complete the following information):**
 - OS: [e.g. Windows] Ubuntu 20.04.4 LTS
 - Blender Version: [e.g. 2.91] 3.0.1
 - Addon Version: [e.g. 0.6.0] 0.6.9 (nice)
 - Did you download a release or build the addon yourself: [e.g. downloaded a release] downloaded a release
 - Related Game: [e.g. CS:GO] Half-Life 2

**Additional context**
I tried doing `pip3 install --upgrade numpy` didn't fix it

**Comment by lasa01** [comment]
This seems to be a problem with your Blender installation (which should
come with a functional numpy). I can't help you with fixing that, but in
any case should try the newest beta release of the addon since it no longer
requires numpy.

**Comment by TheAwesome98-Real** [comment]
how do i get a beta release? just build from source?

**Comment by lasa01** [comment]
[Here](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3).

**Comment by TheAwesome98-Real** [comment]
thanks, that's fixed it
