### ISSUE TITLE
CrowbarCommandLineDecomp.exe - This application could not be started

### ISSUE THREAD

**Issue by SpringySpringo** [lasa01/io_import_vmf#135]
When importing pl_swiftwater_final1 I get this error: ![image](https://user-images.githubusercontent.com/63305176/182266965-dd1810b5-cd17-44ed-aa33-0f67bc288674.png)

Does anyone know why this occurs and how to fix it?

**Comment by lasa01** [comment]
You are probably missing .NET Framework 4.0. Anyway, I would recommend you try the [latest beta version](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3) instead.
