### ISSUE TITLE
Map Materials Empty

### ISSUE THREAD

**Issue by SPAAAAAAAAACE-Core** [lasa01/io_import_vmf#137]
**Describe your problem**

I'm trying to get a map from Portal 2 I made to make a thumbnail for it. But when I import it, the materials are there, they're just white, with no nodes in it either. I'm using Blender 3.21 and made the maps with BEEMOD 2.4.41.

---

**Checklist:**
 - [✓] I have read the README and it doesn't solve my problem.
 - [✓] I have read the FAQ (in the wiki) and it doesn't solve my problem.
 - [✓ ] I have searched previous issues for the problem.

**Comment by SPAAAAAAAAACE-Core** [comment]
If you need more data, I can provide. Also I just used the General Portal 2 game directory
![image](https://user-images.githubusercontent.com/77641752/183259363-9d176995-de7e-4dac-b05f-84c5a754a6ea.png)

**Comment by lasa01** [comment]
If you have errors about missing materials in the console, the game configuration is probably wrong.

I would recommend you try the [latest beta release](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3) since it no longer requires manual configuration.

**Comment by SPAAAAAAAAACE-Core** [comment]
> If you have errors about missing materials in the console, the game configuration is probably wrong.
> 
> I would recommend you try the [latest beta release](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3) since it no longer requires manual configuration.

Thanks I'll try that, For some reason github didn't notify me you replied.

**Comment by SPAAAAAAAAACE-Core** [comment]
Seems Good, but there isn't a Portal 2 option, do I need to add it?

**Comment by SPAAAAAAAAACE-Core** [comment]
Actually it's just a problem with me, thanks for the help.
