### ISSUE TITLE
.mdl import imports body groups for one model but not another

### ISSUE THREAD

**Issue by BenLubar** [lasa01/io_import_vmf#138]
**Describe the bug**
(It's easiest for me to describe this bug as reproduction steps.)

**To Reproduce**
1. Download Alien Swarm (appid 630) or Alien Swarm: Reactive Drop (appid 563560).
2. I'm using the contents of AS:RD's pak01_dir.vpk before it gets packed as part of the build process; if you want to replicate this, use a tool like gcfscape to copy the contents of pak01_dir.vpk to the folder it's located in.
3. Import models/aliens/drone/drone.mdl and models/aliens/parasite/parasite.mdl.
4. Drone has 16 body groups, which are all successfully imported.
5. Parasite has 2 body groups, but only one is imported.
6. (That was all using BST, if I try using SourceIO, it fails even though I do have it installed, but if I try to use it directly, it does import the second body group for parasite.mdl.)

**Expected behavior**
parasite.mdl should import both the (yellow, tail) parasite body group (which it does) and the (red, sac) xenomite body group (which it does not currently do).

**Related files**
Files can be obtained via steam://install/630 or steam://install/563560

**Logs**
```
Read prefs: C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend
Registered nodes
Indexing game files...
Indexing done in 1.0299458503723145 s
Importing model...
[VERBOSE] Staging model models\aliens\drone\drone
[VERBOSE] Loading all models...
[VERBOSE] Importing model models\aliens\drone\drone...
[VERBOSE] Loading all materials...
[VERBOSE] Building material materials/models/aliens/drone/dronek...
[VERBOSE] Building material materials/models/aliens/drone/dronek2...
[VERBOSE] Building material materials/models/aliens/drone/dronek2gored...
[VERBOSE] Building material materials/models/aliens/drone/claw...
[VERBOSE] Building material materials/models/aliens/drone/bonesa...
Game files already indexed
Importing model...
[VERBOSE] Staging model models\aliens\parasite\parasite
[VERBOSE] Loading all models...
[VERBOSE] Importing model models\aliens\parasite\parasite...
[VERBOSE] Loading all materials...
[VERBOSE] Building material materials/models/aliens/parasite/parasite...
[VERBOSE] Building material materials/models/aliens/parasite/claw...
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4257305/185188758-5facb53d-cbf8-4fdb-9211-f2ee7c1f1514.png)

**Details (please complete the following information):**
 - OS: Windows 10 x64
 - Blender Version: 3.2.2
 - Addon Version: 0.6.9
 - Did you download a release or build the addon yourself: built myself; only change was to add some extra prop model classnames to the vmf importer
 - Related Game: Alien Swarm / Alien Swarm: Reactive Drop

[system-info.txt](https://github.com/lasa01/io_import_vmf/files/9364510/system-info.txt)

**Additional context**

**Comment by lasa01** [comment]
This seems like an issue with BST. In any case, I would recommend you try the [latest beta release](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3) since 0.x won't be updated anymore. I checked it quickly and it seems to import correctly with 1.0-beta3.

**Comment by BenLubar** [comment]
Will switch to the beta. Thanks!
