### ISSUE TITLE
Embedded bsp textures no longer working/missing

### ISSUE THREAD

**Issue by matty45** [lasa01/io_import_vmf#14]
Steps to replicate:
1. decompile a vmf using bspsource making sure to tick extraction of embedded files
2. load vmf in blender pointing towards embedded files path

![](https://i.imgur.com/0c78Wb2.png)
![](https://i.imgur.com/etdgClB.jpg)

Edit: Seems that using simple materials makes them be found again.

Issue was found using 6c6f2621215dc4b9349fe2ceea121a814dd41853

**Comment by lasa01** [comment]
It is working just fine for me. Are you on the release or the latest github
version? Are there any errors in the console?

**Comment by matty45** [comment]
ok, that was weird, it seems reimporting it twice without closing blender fixes it, no idea what causing it not to find the textures

**Comment by matty45** [comment]
using latest github version btw

**Comment by matty45** [comment]
turns out it was the embedded materials directory that was the issue, if i dont specify anything, everything works fine

**Comment by lasa01** [comment]
What directory did you specify? If you want to use embedded materials,
you'll need to specify the directory containing the `materials` directory,
not the `materials` directory itself.

**Comment by matty45** [comment]
specified the directory containing the materials folder

**Comment by lasa01** [comment]
If using simple materials fixes it, the problem is most likely with the material files. Check the console for any material related errors.

**Comment by matty45** [comment]
ive narrowed the problem down to specifiying that folder, everything else works fine.

**Comment by lasa01** [comment]
In any case, can you enable verbose logging and send the logs from the console?

**Comment by matty45** [comment]
Logs: https://pastebin.com/P7C5s4L3

**Comment by lasa01** [comment]
From those logs it seems that the embedded directory you specified doesn't exist. Maybe you specified the path relative to the .vmf file, which would not work. You need to specify absolute paths.

**Comment by matty45** [comment]
ah, no wonder why stuff did not work, i feel like such a dumbass

sorry for wasting your time

**Comment by lasa01** [comment]
To be honest, it's a bit confusing especially since it doesn't even give
errors about the directory not existing. I'll add support for relative
paths and make the error more clear.
