### ISSUE TITLE
Parser doesn't know what a hidden block is

### ISSUE THREAD

**Issue by TobyMaddix** [lasa01/io_import_vmf#143]
**Describe the bug**
The parser belives that a hidden block is a duplicated solid.

**To Reproduce**
Import any map with hidden brushes.

**Expected behavior**
The brushes should import and be shown as hidden in the editor.

**Logs**
Could not parse vmf: duplicate field `solid` at line 70729, column 7

**VMF Example**
hidden
{
solid
{
sides....
}
}
solid{
sides....
}

the second solid will error out due to the previous being hidden.

**Comment by Mooshua** [comment]
Temporary workaround:
- Open Hammer
- In the "Auto" visgroups, ensure all items are checked
- In the "User" visgroups, ensure all items are checked
- Ensure cordon mode is off
- Save the file and re-import
