### ISSUE TITLE
Certain props fail to import

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#15]
The latern props from the TF2 japan pack fail to import. 

`QC IMPORTER: now working on hanging_rope_lanterns01.qc
 WARNING: Skipping "hanging_rope_lanterns01_anims\idle.smd"; no armature found.
 WARNING: Skipping fps 0.01; no armature found.
 WARNING: Skipping fps 0.01; no armature found.
QC hanging_rope_lanterns01.qc imported in under 1 second

ERROR LOADING PROP: 'NoneType' object has no attribute 'a'
Done in 0.015503406524658203 s
Imported 0 overlays (0) failed
Imported 0 props (1 failed)
Indexing game files...
Indexing done in 15.43020248413086 s`

If importing a full map with a bunch of props, these failed props become the same model as other existing props. Maybe find a way to turn failed props into something more stand out and obvious? Importing them standalone with Crowbar and Blender Source tools results no failure. Importing the decompiled model stored where created by blender VMF importer, also results in no failure with blender source tools. https://i.imgur.com/r9xRbE0.png

Here is the contents made by the VMF importer: https://drive.google.com/file/d/1u_jD9wPHwU_K-csTffGIoEIFVEQF1tmS/view?usp=sharing

Note, a few other latern props within this pack also fail.

**Comment by lasa01** [comment]
Should be fixed now.
