### ISSUE TITLE
Boss, I strongly request a Mac version!!!!!! I really need it. Thank you very much.

### ISSUE THREAD

**Issue by heyeboine** [lasa01/io_import_vmf#160]
Boss, I strongly request a Mac version!!!!!! I really need it. Thank you very much.！！！！！！！

**Comment by heyeboine** [comment]
> 您是否尝试过 Plumber 测试版？它可以在发布页面上找到并支持 Mac。

Excuse me, what should I search for, boss? There are too many choices to search only for this keyword.

**Comment by heyeboine** [comment]
> 您是否尝试过 Plumber 测试版？它可以在发布页面上找到并支持 Mac。

sorry boss，i don't know its own you

**Comment by lasa01** [comment]
Here: https://github.com/lasa01/io_import_vmf/releases

**Comment by heyeboine** [comment]
> 这里： https: [//github.com/lasa01/io_import_vmf/releases](https://github.com/lasa01/io_import_vmf/releases)

Thank you. I can already import MDL files on the Mac. Where can I support you? You helped me solve a big problem. Thank you very much!

**Comment by lasa01** [comment]
Glad to see the issue solved. You can star the repository for support. I can't really accept donations unfortunately.
