### ISSUE TITLE
Some materials aren't getting imported properly

### ISSUE THREAD

**Issue by CatastrophicDino** [lasa01/io_import_vmf#163]
**Describe the bug**
I'm trying to import de_aztec (CS:S) into blender but some textures aren't importing correctly.

**To Reproduce**
Decompile de_aztec from Counter Strike Source using BSPSource
Import de_aztec_d into blender

**Expected behavior**
All materials imported and get applied

**Related files**
[de_aztec_d.txt](https://github.com/lasa01/io_import_vmf/files/11269186/de_aztec_d.txt) (rename .txt to .vmf)

**Logs**
[Pastebin](https://pastebin.com/0tRmRGA6)

**Screenshots**
Correct:
![image](https://user-images.githubusercontent.com/47283350/232981272-def54695-8d83-49af-9f17-e1c3cefe90bf.png)
Incorrect:
![image](https://user-images.githubusercontent.com/47283350/232981549-0812ea35-431c-4145-b725-aa961b592325.png)
Game Config:
![image](https://user-images.githubusercontent.com/47283350/232982144-362a40d4-0fdd-48e5-a06b-297ed0a0163d.png)

**Details (please complete the following information):**
 - OS: Windows
 - Blender Version: 3.5.0
 - Addon Version: 0.6.9
 - Did you download a release or build the addon yourself: release
 - Related Game: CS:S

**Additional context**
I re-imported the map several times after changing settings because the first import wasn't configured correctly

**Comment by lasa01** [comment]
Looks like the materials were not found. Make sure you checked "extract embedded files" in bspsource when decompiling. If the materials are still missing, the game configuration is probably wrong. In that case, you can try the latest Plumber beta version which can be found on the releases page, since it has automatic game configuration.

**Comment by CatastrophicDino** [comment]
ok now it works thanks
