### ISSUE TITLE
Unable to display and import vmat

### ISSUE THREAD

**Issue by Qfather** [lasa01/io_import_vmf#164]
**Describe the bug**

**To Reproduce**
1. Import vmat

File browser does not recognize Vmat

**Details (please complete the following information):**
 - OS: [e.g. Windows10]
 - Blender Version: [e.g. 3.50]
 - Addon Version: [e.g. 0.6.9]
 - Related Game: [DOTA2]

![Snipaste_2023-06-18_10-57-55](https://github.com/lasa01/io_import_vmf/assets/83439586/7f6a710d-d532-46c9-9cb8-9304b8084c97)

**Comment by lasa01** [comment]
Unfortunately Source 2 games are not supported and there are currently no plans to add support. You can try SourceIO for importing Source 2 materials.
