### ISSUE TITLE
Slow import times

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#2]
Dont mind me, just putting this up so I can ask about some possibilities, im loving this addon!
Would it be possible within the near future to split the workload between threads? Or doing dirty, and just having multiple instances of the software work on different chunks of a .vmf at a time?

**Comment by lasa01** [comment]
By far the most time is spent importing prop models. Performance optimizations for the model importer would need to be either done in Blender Source Tools or I would need to create a new model importer for the addon. This is definitely not a priority at the moment, but I might consider it in the future.

**Comment by LethalDumpster** [comment]
I see. Would there atleast be a way to cache and skip already ported models(as fbx) within a directory? I understand that may sound odd, but while testing same or even multiple maps, I think it was obviously getting redundant. FBX should import to blender faster anyway.

**Comment by lasa01** [comment]
It could be possible to use library .blend files to cache the imported data. The native blend format would probably work better than fbx or other alternatives. With 49e970b947774ee4afc2cdbcca8b1ea457ecc54f and f0df6d04cb6f20fb8743d5d619aee3a7da4eccc2, all the required information to recreate previously imported data is now saved to the .blend file, so adding an external cache should be feasible.

**Comment by LethalDumpster** [comment]
I used the tool to get a bunch of pretty renders in blender, but I was also doing a bit of porting to UE4. Most efficient way for me to do that with multiple maps, would be to somehow get every mesh FBX dumped into a directory. And then UE4 only import what it hasnt before from the directory. The step above that is probably having a file with model names and transform data for each map. 

If I could get such a model transform file from blender that points to the FBXs it dumped. Aswel as the FBXs pointing to their respective dumped textures. I would be able to use that file in UE4, to tell UE4 where to place everything after I import the dumps myself. This is actually very similar to some of the COD porting tools. It tool a bit of manual work myself, but it accomplished just that

**Comment by lasa01** [comment]
This is fixed in Plumber 1.0.0 beta versions, you can try the latest version [here](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3).
