### ISSUE TITLE
Fitting skybox onto map does not work properly.

### ISSUE THREAD

**Issue by matty45** [lasa01/io_import_vmf#20]
Steps to replicate:
1. Import the vmf
2. Select the whole skybox while keeping skybox camera as active
3. Transform the skybox

![](https://i.imgur.com/en7z4OT.jpg)

It seems the issue is that the skybox camera for some reason is rotated to 35 degrees causing the skybox to be rotated wrongly.

**Comment by lasa01** [comment]
Does setting the rotation to 0 fix it? Or should it be negated? If it's
rotated it means the sky_camera is rotated in the .vmf file too. I didn't
find any information on how the rotation is handled though so it's probably
incorrect.

**Comment by matty45** [comment]
Yeah, i forgot to mention that setting it to zero fixes it, sorry

**Comment by lasa01** [comment]
Should be fixed now.
