### ISSUE TITLE
Terrain distortion on imported vmf (not decompiled)

### ISSUE THREAD

**Issue by matty45** [lasa01/io_import_vmf#22]
I imported a original vmf file to see that there were some problems with the displacements on the mesh.

[VMF Download](https://www.dropbox.com/s/cd2qw4ros33ihx1/gm_fork_source.zip?dl=1)

Hammer:
![](https://i.imgur.com/X6lRUzQ.jpg)

Blender:
![](https://i.imgur.com/rToZ0hu.jpg)

**Comment by lasa01** [comment]
Should be fixed now.

**Comment by matty45** [comment]
Thanks, i really appreciate you fixing things this fast.
