### ISSUE TITLE
Question: What is the best format to export with?

### ISSUE THREAD

**Issue by matty45** [lasa01/io_import_vmf#25]
Was wanting to mess around with the vmf in other programs but i cant seem to export them without losing all the normal maps.

Have tried using fbx and dae but they dont seem to export very well.

**Comment by LethalDumpster** [comment]
FBX. I have no issue using FBX. I port to UnrealEngine4 often. The issue with normal maps, is that 99% of model types only support direct connections of textures. But this addon created materials with complicated connections for graphical purposes. Solution is to import your map with 'Simple materials' checked.

**Comment by matty45** [comment]
Wish there was a way to preserve the normal and specular maps :(

**Comment by lasa01** [comment]
Fbx should preserve at least the normal maps (but only if you have the
simple materials enabled). You could also look into gltf if it works with
the software you're using, it has a pretty good support for different kinds
of materials (you still need to check simple materials).

**Comment by matty45** [comment]
Allright, thanks
