### ISSUE TITLE
add an enhanced mdl import option (decompile)

### ISSUE THREAD

**Issue by Xephobia** [lasa01/io_import_vmf#26]
The concept : currently when you import an mdl it import with SourceIO, that addon is cool but not complete and has issues with charachter models. So my suggestion would be to add an option to decompile the mdl using crowdbar and importing the qc and smds using blender source tools, similar to qc import but that would be automatic

**Comment by lasa01** [comment]
This feature is added now.

**Comment by Xephobia** [comment]
thanks!
