### ISSUE TITLE
Latest SourceIO master is not supported

### ISSUE THREAD

**Issue by loliXn** [lasa01/io_import_vmf#28]
![image](https://user-images.githubusercontent.com/20803376/84060213-80ee3380-a9c4-11ea-9903-a1755eb2036d.png)
as the title says, apparently addon can't detect installed SourceIO. I'm using latest master build of SourceIO and latest version of your addon.
![image](https://user-images.githubusercontent.com/20803376/84060454-e6422480-a9c4-11ea-9d1e-dfb7bbc1d0bd.png)

**Comment by lasa01** [comment]
The addon folder needs to be named "SourceIO" for it to work. Your seems to
be named "SourceIO-master", which will not work.

**Comment by loliXn** [comment]
just tried to rename the addon folder, unfortunately that didn't work for me. any ideas what else could cause this?
![image](https://user-images.githubusercontent.com/20803376/84061831-45089d80-a9c7-11ea-9ab7-d73df3aeaa76.png)

**Comment by lasa01** [comment]
Actually looks like the latest master branch of SourceIO has lots of
breaking changes, so it is not supported.

**Comment by loliXn** [comment]
it actually may be it because dev switched to the new experimental importer script so that might have been the case all along.

**Comment by lasa01** [comment]
Looks like the new code is very difficult to integrate with, and since importing .mdl is already supported with BST and automatic decompilation, this won't be fixed. I added a better "unsupported version" error for now.
