### ISSUE TITLE
No apparent skybox origin

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#3]
This obviously being the skybox camera. Having it appear as a blender Empty Axis would allow for easily fitting the skybox to the map and scaling it up.

**Comment by lasa01** [comment]
Good idea, I will look into implementing this.

It would be better to automatically move the 3d skybox to the correct position, however it is not easy to distinguish which props/brushes are part of the 3d skybox and which are part of the map itself.

**Comment by matty45** [comment]
the way wallworm does it is that you have to select the whole 3d skybox then press a button to scale it up to fit the actual map

**Comment by lasa01** [comment]
Added support for this. Also added a tool to help with resizing and repositioning the sky objects as suggested: just select everything that is part of the sky, then select the imported sky_camera (empty object) as the active object, and use Object -> Transform VMF 3D sky from the 3D view.
