### ISSUE TITLE
weird error when importing

### ISSUE THREAD

**Issue by Xephobia** [lasa01/io_import_vmf#33]
Indexing game files...
Importing model...
Importing model hwn2018_crocodile_mun_dee...
C:\Users\xeph\Desktop\hwn2018_crocodile_mun_dee\hwn2018_crocodile_mun_dee.mdl
D:\decompiledmodels\
Decompiling with Crowbar 0.68: "C:\Users\xeph\Desktop\hwn2018_crocodile_mun_dee\hwn2018_crocodile_mun_dee.mdl" ...

Decompiling ".\hwn2018_crocodile_mun_dee.mdl" ...
Model version overridden to be 48.
Reading MDL file header ...
... Reading MDL file header finished.
Checking for required files ...
... All required files found.
Reading data ...
Reading MDL file ...
... Reading MDL file finished.
Reading VTX file ...
... Reading VTX file finished.
Reading VVD file ...
... Reading VVD file finished.
... Reading data finished.
Writing data ...
Reference mesh files:
hwn2018_crocodile_mun_dee.smd
Vertex animation files:
hwn2018_crocodile_mun_dee_01.vta
... Writing data finished.
... Decompiling ".\hwn2018_crocodile_mun_dee.mdl" finished.

Traceback (most recent call last):
  File "C:\Users\xeph\Desktop\app\blender-2.83.0-windows64\scripts\addons\io_import_vmf\__init__.py", line 922, in execute
    qc_importer.load(splitext(relpath(self.filepath, root))[0], self.filepath, context.collection, root)
  File "C:\Users\xeph\Desktop\app\blender-2.83.0-windows64\scripts\addons\io_import_vmf\import_qc.py", line 235, in load
    return self.load_return_smd(name, path, collection, root).a
  File "C:\Users\xeph\Desktop\app\blender-2.83.0-windows64\scripts\addons\io_import_vmf\import_qc.py", line 212, in load_return_smd
    raise Exception(f"Decompiling model {mdl_path} failed")
Exception: Decompiling model hwn2018_crocodile_mun_dee.mdl failed

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by lasa01** [comment]
Looks like the decompiled model couldn't be found. Can you manually check
the contents of the folder "D:\decompiledmodels"? There should be a .qc
file of the model.

**Comment by Xephobia** [comment]
it's weird it has the smd but not the qc. I decompiled the model manually and it worked

**Comment by lasa01** [comment]
Does this happen with other models or only that one? Also, Crowbar-Command-Line was recently updated and now uses the settings of normal Crowbar, so if you have changed the decompiling settings (such as disabled qc file generation) it can fail.
