### ISSUE TITLE
Methods for assisting mass ports to other software

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#34]
I used the tool to get a bunch of pretty renders in blender, but I was also doing a bit of porting to UE4. Most efficient way for me to do that with multiple maps, would be to somehow get every mesh FBX dumped into a directory. And then UE4 only import what it hasnt before from the directory. The step above that is probably having a file with model names and transform data for each map.

If I could get such a model transform file from blender that points to the FBXs it dumped. Aswel as the FBXs pointing to their respective dumped textures. I would be able to use that file in UE4, to tell UE4 where to place everything after I import the dumps myself. This is actually very similar to some of the COD porting tools. It took a bit of manual work myself, but it accomplished just that

**Comment by lasa01** [comment]
Closing this since porting to other software is outside the scope of this project.
