### ISSUE TITLE
Tutorials for how to build

### ISSUE THREAD

**Issue by phoondos** [lasa01/io_import_vmf#35]
I tried building the source and had a lot of trouble with it, but when I got a build to import into blender, it would give me an error with any vmf I imported. It would be a great help if there was a tutorial for how to correctly build the source code.

**Comment by lasa01** [comment]
The readme already has a small section for this. You just need to
download/clone the repository, run the install script (.sh for linux, .ps1
for windows) and then in Blender, install the .zip that gets created in the
same directory.

If you still get any errors please send them here.

**Comment by phoondos** [comment]
Yes, I followed it best I could and couldn't import any maps; I kept getting an error when importing.

**Comment by lasa01** [comment]
The build script should be working. Please open Blender's console from
(Window -> Toggle system console) and try to import something. After it
fails, send the messages that were printed into the console here.

**Comment by phoondos** [comment]
Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_import_vmf\__init__.py", line 737, in execute
    importer.load(self.filepath, context, self.map_data_path)
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_import_vmf\import_vmf.py", line 160, in load
    self._qc_importer.load_all()
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_import_vmf\import_qc.py", line 229, in load_all
    self._load(name, staged)
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_import_vmf\import_qc.py", line 298, in _load
    raise FileNotFoundError(mdl_path)
FileNotFoundError: models/props_junk/garbage_plasticbottle003a.mdl

the map just stops importing after this happens and im left with a few models imported

**Comment by lasa01** [comment]
Seems that the addon can't find the required game files, definitely doesn't seem like a building related issue. Could you check that you have configured games correctly and send a screenshot of the addon preferences with the game opened? If all looks good, please tick the "verbose" checkbox before importing, open the Blender console, try to import something and send everything printed into the console here.

**Comment by phoondos** [comment]
[errors.txt](https://github.com/lasa01/io_import_vmf/files/5240870/errors.txt)

**Comment by lasa01** [comment]
That is a different error than what you sent before, but there was a bug and it's fixed now. Also fixed the invalid color syntax errors.
