### ISSUE TITLE
func_door_rotating and other brush entities cause failure

### ISSUE THREAD

**Issue by Fennecai** [lasa01/io_import_vmf#36]
when importing maps with func_brush, func_door_rotating, trigger_catapult, and more, there is an error saying it is not a dict..or something. i don't remember exactly.

this especially happens when importing vmfs created for portal 2; even with correct game setup in the user preferences.

maybe there addon should detect when there are brush entities, and just ignore them? and only import the brush itself, since brush entities are useless in blender.

**Comment by lasa01** [comment]
The addon should import them the same way as normal brushes, the extra functions are not handled in any special way. Seems like there is some kind of bug. Could you open the Blender console before importing, tick the "verbose" checkbox, try to import again and send the messages printed into the console here. Sending the .vmf file that causes the error would also help.

**Comment by Fennecai** [comment]
[sp_a3_giant.vmf.txt](https://github.com/lasa01/io_import_vmf/files/5248858/sp_a3_giant.vmf.txt)


and here is the console:

[log.txt](https://github.com/lasa01/io_import_vmf/files/5248859/log.txt)


...in addition; if it helps, here is a version of the VMF that I've manually fixed to get working:

[sp_a3_giant_blender.vmf.txt](https://github.com/lasa01/io_import_vmf/files/5248860/sp_a3_giant_blender.vmf.txt)

(side-note: there is also a bug where ``info_overlay``s made in portal 2's sdk cause similar problems as a result of the startu, startv, endu, and endv keyvalues all being lowercase when this addon expects uppercase versions as in older versions of source.)

**Comment by lasa01** [comment]
The VMF seems to have a lot of solids that have just a number in them (there should be a whole block of sides and other data). Not sure what's going on with that .vmf, but now it should ignore the weird invalid solids in there. The whole VMF parser is now also case insensitive, so the other problem should be fixed too.
