### ISSUE TITLE
no module named 'vmfpy' error (Blender 2.82)

### ISSUE THREAD

**Issue by jhm0799** [lasa01/io_import_vmf#37]
I installed the Source Tools (version 3.1.0) and then tried to install this addon. However, when I tried to enable it, it gave me the error shown in the screenshot. Does this addon rely on a specific version of Source Tools? If so, which one?
![vmfpy](https://user-images.githubusercontent.com/29484887/93840672-3769e180-fc5f-11ea-9f6f-4218e5a07fcc.png)

Any help would be appreciated... Thanks!

**Comment by lasa01** [comment]
Did you download the released addon or did you build the latest unreleased
version and install it manually? If you built it yourself you probably
didn't run the install.ps1/install.sh script, which must be done since it
downloads some required dependencies.

**Comment by jhm0799** [comment]
I downloaded the release from here

**Comment by lasa01** [comment]
What's the file you downloaded called? It it's called `io_import_vmf-master.zip`, you downloaded the wrong thing, you should download `io_import_vmf.zip` from the releases.

**Comment by jhm0799** [comment]
Yep, downloaded that. Same thing. Forget it... Not going to waste any more time on it.
