### ISSUE TITLE
2.79 and older too?

### ISSUE THREAD

**Issue by ALIEN31ITA** [lasa01/io_import_vmf#38]
it shouldn't be so hard to do this... i have nothing against 2.8, it's just plugin compatibility reasons

**Comment by lasa01** [comment]
The material node setups depend on a feature introduced in Blender 2.82 (Map Range node interpolation modes). Without that it is impossible to implement correct blending in WorldVertexTransition materials. There are also other differences, breaking changes and so on. Supporting both versions would be too much work, so 2.79 will not be supported.
