### ISSUE TITLE
Missing model causes whole VMF import to fail

### ISSUE THREAD

**Issue by loliXn** [lasa01/io_import_vmf#41]
![image](https://user-images.githubusercontent.com/20803376/95467730-76e63c80-0986-11eb-8ccc-548afe6075d2.png)
Somehow while trying to import (newest 0.5.1 addon release) default gm_construct map it only imported alyx doll prop and absolutely nothing else. Tried to play around with various settings, but everything seemed to give the same results (only the LOD option generated 4 more lod models of alyx doll). The 0.4.1 version of addon was working arguably fine (half of the textures weren't loading for some reason, but at least all of the brushes/models loaded correctly) with gmod maps, so I'm guessing that this issue is somehow related to the new code. 

The settings I used in BSPSource: 
![image](https://user-images.githubusercontent.com/20803376/95468041-cd537b00-0986-11eb-86a7-5e0aa508b9e3.png)

The paths of your addon: 
![image](https://user-images.githubusercontent.com/20803376/95468154-e4926880-0986-11eb-8e9e-219d1a655ade.png)

The settings in the import window: 
![image](https://user-images.githubusercontent.com/20803376/95468289-0855ae80-0987-11eb-8679-4b25bffde79b.png)

**Comment by LethalDumpster** [comment]
Most Garry'smod maps also direct from ofcourse HL2 assets. So check around for HL2 related vpks.

**Comment by loliXn** [comment]
I'll try, thanks for the advice (but that is kinda strange, because on the previous version everything worked with the same settings)

**Comment by lasa01** [comment]
Changes in the newer versions cause the import to instantly fail if a model is missing, in previous versions an error would be printed in the console and the model would be just skipped.

The old behavior was definitely better, so let's keep this open. The error message could also be improved.

**Comment by lasa01** [comment]
This is maybe fixed now, at least I hope it is.
