### ISSUE TITLE
SyntaxError: vdf.parse: unexpected EOF (open key quote?)

### ISSUE THREAD

**Issue by pac0master** [lasa01/io_import_vmf#47]
I'm trying to load one of my VMF and it just doesn't work at all.

I can load it just fine in hammer, so I don't understand what's the problem.
![image](https://user-images.githubusercontent.com/21280760/100520803-d0d8d680-316d-11eb-8907-ea8bfdaefc56.png)

I also tried using the backup VMX but the same thing happens

**Comment by lasa01** [comment]
Can you send the vmf file?

**Comment by pac0master** [comment]
Look up your mails.

**Comment by lasa01** [comment]
Should be fixed now.
