### ISSUE TITLE
Trigger_Hurt brushes dont appear to port.

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#48]
This was tested with pl_upward of TF2.

**Comment by lasa01** [comment]
I don't see why they wouldn't get imported as long as you enable importing invisible tools. Can you send the .vmf file?

**Comment by LethalDumpster** [comment]
[pl_upward_d.zip](https://github.com/lasa01/io_import_vmf/files/5612957/pl_upward_d.zip)

**Comment by lasa01** [comment]
Actually trigger brushes aren't imported at all, only func brushes. Should be relatively easy to fix.

**Comment by lasa01** [comment]
Done.
