### ISSUE TITLE
No sky material on port in place of HDRI

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#5]
It appears no sky material has been made for the world background. If capable, maybe an option to automatically import the sky material and turn on/setup nodes for it.

**Comment by lasa01** [comment]
The biggest issue with this is that Blender doesn't support skyboxes, only equirectangular and mirror ball projections.

It could be possible to convert the skybox into an equirectangular texture. I found [this](https://github.com/sunset1995/py360convert), but it depends on scipy which is very large, bundling it with the addon would be a bad idea.

**Comment by LethalDumpster** [comment]
It should be possible to manually convert via 360 render inside a cube for the quick and dirty users. But locating skybox textures by hand is sure a pain. But even if not, if somone were to use that plugin themselves, they still need locate the textures. Maybe an un-plugged texture sample withing the world background material? Just until a clean solution is found, so folks can easily go about their own.

**Comment by LethalDumpster** [comment]
Might this be useful?(if somethings not already found or being worked on :P) https://github.com/adamb70/Python-Spherical-Projection

**Comment by lasa01** [comment]
The first one seems promising. I will look into adding a skybox converter based on it to the addon.

**Comment by lasa01** [comment]
This is implemented now. Tested it on some CSGO maps and seems to work fine.

The sky is too bright sometimes, but the strength can be manually adjusted. I will look into fixing that.
