### ISSUE TITLE
Import sky at original resolution

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#52]
A checkbox to import skies at what would be their full original resolution would be fantastic

**Comment by lasa01** [comment]
Blender doesn't support skyboxes, so the skybox is converted into an equirectangular texture. The conversion is lossy regardless of the resolution, so importing at full original resolution is not possible.

**Comment by LethalDumpster** [comment]
I'm not 100% on how lossy works. But of what I understand, there is still a resolution in terms of height from the bottom skybox, to the top of the skybox. >in the original texture
Of course with how its formatted, it would only be part way into the bottom and top. 
![image](https://user-images.githubusercontent.com/37680558/100643074-38725b80-32ff-11eb-83fe-db36ba6c18c9.png)

But couldn't that height be transferred to the image height of the new image?
It would appear the difference oughta be to subtract 1/3 the original pixel height. So 4k would become about 2,667(rounded) pixels tall.

**Comment by lasa01** [comment]
The addon converts the following cubemap:
![cubemap](https://i.stack.imgur.com/Q1SO4.png)
Into the following format:
![equirectangular](https://i.stack.imgur.com/czqlM.png)
Looking at that, yeah it would make sense to set the default resolution to 4x the width and 2x the height of an individual cubemap face by default like you suggested, though there would still be some data lost in the conversion. It's at least better than the current static default resolution so I'll try to implement it.

**Comment by LethalDumpster** [comment]
Not sure about '4x' width and '2x' height. Unless I'm understanding you differently.
But aside warping, width is technically unchanged. And height is just one third less.
![image](https://user-images.githubusercontent.com/37680558/100678472-dcc1c580-3332-11eb-8b8c-ad21b097d9f5.png)
A width of 8k, is still 8k.
Whats mostly cut down is the top and bottom square. And their both cut by half. 2k total cut down on height, out of what was originally 6k. Which equals 4k of height on the new image. So again, just -1/3 pixel height.

**Comment by lasa01** [comment]
I meant 2x and 4x of a single cubemap side. The sky cubemaps are stored as
six individual images in source games, one for each side, not as a single
image.

**Comment by LethalDumpster** [comment]
Yup, took me way too long to realize that :P
