### ISSUE TITLE
When I import the zip file into blender it doesn't show up

### ISSUE THREAD

**Issue by Amberwoodwastaken** [lasa01/io_import_vmf#56]
**My add on doesnt work coz when i import it nothing happens and when i search for it it doesnt show up

Yes i imported the zip file

Yes i tried re downloading the add on again

Yes i have the "testing" tab enabled as well in the add on tab

Yes i restarted my pc and blender**

**Comment by lasa01** [comment]
What's the file you downloaded called?

**Comment by Amberwoodwastaken** [comment]
> What's the file you downloaded called?

io_import_vmf-master.zip

**Comment by lasa01** [comment]
That's the wrong file. You need to download from the releases page like the
instructions say.

**Comment by Amberwoodwastaken** [comment]
> That's the wrong file. You need to download from the releases page like the instructions say.

thanks that fixed it! im new to blender so sorry for wasting ur time
