### ISSUE TITLE
Emission textures not always being added to materials

### ISSUE THREAD

**Issue by LethalDumpster** [lasa01/io_import_vmf#6]
As seen in this screenshot, emission textures simply arent being added. Only using the Alphas of other textures.
https://i.imgur.com/ZWdWGZt.png

Alphas do work in some cases, but require an extra node.
https://i.imgur.com/0dC0c39.png

**Comment by LethalDumpster** [comment]
Have you looked into utilizing the mix node for atleast when alpha's are being used?

**Comment by lasa01** [comment]
I fixed this already (using multiply node instead, works just as well). You
can install the latest master branch (README has instructions) if you want
to test it.

**Comment by LethalDumpster** [comment]
Many thanks!
