### ISSUE TITLE
Can't enable latest version

### ISSUE THREAD

**Issue by Maker261** [lasa01/io_import_vmf#60]
I'm using 2.91 to install the addon, bute I can't seem to be able to enable it at all
whats the issue about this?
![Screenshot_6](https://user-images.githubusercontent.com/46901949/104709090-2b7ebf80-5727-11eb-8e5c-5f49ab49811e.png)

**Comment by Maker261** [comment]
Don't tell me, I have to restart the whole system before I can enable it?
Cause thats exactly what happened. I booted my pc back up, tried enabling the addon again and it worked this time.

**Comment by lasa01** [comment]
That's pretty weird, restarting shouldn't make any difference.
