### ISSUE TITLE
Only worldspawn is imported

### ISSUE THREAD

**Issue by Maker261** [lasa01/io_import_vmf#61]
I remember getting the stuff from gmod maps like a charm before, but now I've reinstalled my system and I have forgotten what I did to also get the foliage and props and such into blender.
What am I missing?
![Screenshot_7](https://user-images.githubusercontent.com/46901949/104731994-30eb0280-5745-11eb-9f9a-ef7bd4a3c4a5.png)
![Screenshot_8](https://user-images.githubusercontent.com/46901949/104732000-32b4c600-5745-11eb-961d-697dcf9c0c89.png)

**Comment by Maker261** [comment]
Appearently you gotta open blender as administrator in order for the addon to work entirely or else it'll only work for worldspawn.
Not sure if this is a restriction or a bug tbh

**Comment by lasa01** [comment]
It should work without opening as administrator. This sounds like some kind of permission issue. Are there any errors in the console?

**Comment by Maker261** [comment]
nope, no error whatsoever
