### ISSUE TITLE
Can't find io_scene_valvsource

### ISSUE THREAD

**Issue by webbywebbers** [lasa01/io_import_vmf#62]
Every time I try to import a vmf I keep getting the same
```
ModuleNotFoundError: No module named 'io_scene_valvsource'
```
I'm pretty sure I installed everything correctly, and I set the cache to io_import_vmf_cache.
How can I fix this?

**Comment by lasa01** [comment]
Seems like you didn't install Blender Source Tools.

**Comment by webbywebbers** [comment]
Hmm. I thought I did but this error keeps coming up for all the files. 
<img src="https://cdn.discordapp.com/attachments/795317932837699607/801520958086316052/Capture.PNG" alt="error">

**Comment by webbywebbers** [comment]
nvm
