### ISSUE TITLE
Portal Maps not importing materials/props

### ISSUE THREAD

**Issue by Sk3leCreeper** [lasa01/io_import_vmf#64]
I'm trying to import some portal maps and when I do, no materials get imported and no props do either. All of the hl2 and portal directories and vpk files are mounted in the addon settings, so I have no idea why it isn't detecting the materials and models. The errors in the console are that it can't find the materials and props even though the vpks that they exist in are mounted in the settings. The addon has worked fine in the past importing tf2 and half life 2 maps.

**Comment by lasa01** [comment]
It should work if everything is configured correctly. Can you send a screenshot of the settings and double check you selected the correct game definition in the import dialog?

**Comment by Sk3leCreeper** [comment]
Oh, I am a dumb dumb. It appears that I did not notice you had to choose the game on the import dialogue, after actually noticing it and changing it the map imports fine ._.
