### ISSUE TITLE
non-standard vmt fix

### ISSUE THREAD

**Issue by ArclightReflex** [lasa01/io_import_vmf#68]
Yeah when I tried to import some custom map from garrysmod & sourcefilmmaker.
and some props can't import correctly.
I did some work and found the reason.
Some .vmt materials didn't use the standard {} form
may be like

"VertexlitGeneric"
{
	"$basetexture" "OptiNVfallout\legiontent"
	"$halflambert" "1" }

which cause error when using readline.

it will be good if you make a fix.
thx
XDDDD

**Comment by ArclightReflex** [comment]
I write a simple batch program by adding "\n" one place behind the last "}".
dumb but working.

**Comment by lasa01** [comment]
This is fixed in Plumber 1.0.0 beta versions, you can try the latest version [here](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3).
