### ISSUE TITLE
Missing Texture from maps with content requirements

### ISSUE THREAD

**Issue by Maker261** [lasa01/io_import_vmf#69]
I only know how to get the textures work on maps that don't require any contents from other valve games
But how do I get the textures and materials to work on maps that need like CSS content? Do I need to add another directory that leads to other materials and such? or.....?

**Comment by lasa01** [comment]
It should work if you also use the "detect from game directory" button on
the css's "cstrike" folder.

**Comment by Maker261** [comment]
you mean I need to have the games installed on my pc for the contents to work and not the gmod content addons themselves???

**Comment by lasa01** [comment]
I'm not sure how the content addons work but if you can find the directory
they are in you can try to use the detect on the css content.

**Comment by Maker261** [comment]
Alright, I will try that
