### ISSUE TITLE
[Bug] Nothing imports except for base geometry (maps).

### ISSUE THREAD

**Issue by ChristianSoldier** [lasa01/io_import_vmf#74]
When I try to import a map (.vmf) from Source Filmmaker, it only imports the lights and base geometry.  It doesn't import the textures and materials.  Sometimes, it doesn't even import the props.  Even when I try to import the materials separately, they don't work.
![h](https://user-images.githubusercontent.com/39861797/109394066-0cad4480-78f3-11eb-8f68-d980bd9cb103.JPG)

**Comment by ArclightReflex** [comment]
see my reply in another issue.

**Comment by ArclightReflex** [comment]
Unlike some custom maps,I didn't meet a single error when importing cp_badlands in SFM folder.
https://sta.sh/01h4d8eye7d0
https://sta.sh/04lx1xs2ozw
Are you do some steps wrong?Like forgeting to set game directory?Or don't have IO permission?
