### ISSUE TITLE
Normal/Bumpmaps don't work in Cycles

### ISSUE THREAD

**Issue by fordij** [lasa01/io_import_vmf#75]
Something is wrong with how the plugin imports materials with bumpmaps. The shadows are completely dark, rather than shading normally. I've attached a bunch of pictures with the shader setup and how the materials should look in-game. (Image dump)

**For reference, what it should look like:**
![hl2_2021-02-28_14-46-03](https://user-images.githubusercontent.com/44008438/109431431-9aad2c00-79d4-11eb-99ac-34cabc7fa697.png)
![hl2_2021-02-28_14-46-12](https://user-images.githubusercontent.com/44008438/109431440-a993de80-79d4-11eb-9abd-f45f90f23a58.png)

**Eevee looks fine:**
![blender_2021-02-28_14-48-21](https://user-images.githubusercontent.com/44008438/109431460-c6301680-79d4-11eb-8416-09e82b734043.png)
![blender_2021-02-28_14-48-06](https://user-images.githubusercontent.com/44008438/109431463-c7f9da00-79d4-11eb-9f89-09168d6a67ed.png)

**But then rendering in Cycles ruins the shadows unless I remove the Normal map link in the shader:**
![blender_2021-02-28_14-42-01](https://user-images.githubusercontent.com/44008438/109431471-d0eaab80-79d4-11eb-9946-6082adc67233.png)
![blender_2021-02-28_14-42-012](https://user-images.githubusercontent.com/44008438/109431483-dd6f0400-79d4-11eb-9014-79108e902071.png)
![blender_2021-02-28_14-44-16](https://user-images.githubusercontent.com/44008438/109431485-e1028b00-79d4-11eb-9288-1199057f2f18.png)
![blender_2021-02-28_14-45-39](https://user-images.githubusercontent.com/44008438/109431495-ef50a700-79d4-11eb-99b0-8033bea0e8ab.png)

**Comment by lasa01** [comment]
I assume this is TF2. Which map is this?

**Comment by lasa01** [comment]
Nevermind, I found the issue.
