### ISSUE TITLE
Game Definition not showing up.

### ISSUE THREAD

**Issue by Rainerr123** [lasa01/io_import_vmf#78]
my game definition is not showing up in my import, 

![image](https://user-images.githubusercontent.com/57333628/116241824-e5aaac00-a797-11eb-8aee-01dc75bcb4bf.png)
my settings ^

![image](https://user-images.githubusercontent.com/57333628/116241863-f0654100-a797-11eb-870a-7d2dd39f6f9b.png)
then it still doesnt show up, i can't tell if its the addon or i'm missing something stupid.

**Comment by lasa01** [comment]
Are you using blender 2.93? Someone else reported the same thing, I will
have to check it later.

**Comment by Rainerr123** [comment]
> Are you using blender 2.93? Someone else reported the same thing, I will have to check it later.

yeah its 2.93 fresh install from today

**Comment by lasa01** [comment]
This is fixed in v0.6.1.
