### ISSUE TITLE
hL2 maps importing, Blender hangs for ever

### ISSUE THREAD

**Issue by aidin0181** [lasa01/io_import_vmf#79]
Hi,
Blender will hang when i try to import map into it. it's hl2 bsp map.
i can see the blender is taking cpu power but it always stay in not responding mode, and no cmd text will apear.
so i tried to close blender in cmd by pressing ctrl + c, then suddenly i saw one train imported in the scene and some sort warnings from python addons on blender. 

Is this normal? should i have to wait more?
i'm sorry for asking here, but does it extracts textures too? in order to import in unity.

**Comment by LethalDumpster** [comment]
Enable verbose in the import options before importing. This will feed information into a cmd as you expect it to.

Maps do take a while to import based on map complexities and cpu speed.

**Comment by aidin0181** [comment]
thanks, yeah it took a while to import, i just import lights to see if it's importing.

**Comment by aidin0181** [comment]
problem solved, thanks
