### ISSUE TITLE
Brush vertice inaccuracy with larger imports

### ISSUE THREAD

**Issue by dotrich** [lasa01/io_import_vmf#82]
Any group of brushes that have been rotated off-grid or are off-grid because of clipping tool do not seem to import accurately. The vertices are way off, I suppose within 1 unit. With the same brush (which has vertices off-grid) I copied it into a fresh vmf and it imported fine with no inaccuracies. The vmf took a good 30 minutes to import and the map is quite large taking up 1/4th of Hammer's grid but centered of course. The file size of the vmf is 32,720 KB which is part of a commision so I cannot share it unfortunately.

This may be a flook but it is at least worth reporting. I'm sorry I could not explain better or provide any better evidence.

1. Import a very large, densely populated vmf with off-grid brushwork.
2. Set default options as of 0.6.3
3. Inspect brushwork for inaccuracies.

The black lines are a Hammer DXF export of the brushes and the orange lines are the vmf imported brushes.
https://user-images.githubusercontent.com/4912391/119099911-4f248000-ba0f-11eb-9577-678b99d674f3.png

 - OS: Windows 7
 - Blender Version: 2.81a
 - Addon Version: 0.6.3
 - Downloaded a release
 - Related Game: CS:GO

**Comment by lasa01** [comment]
The vmf size shouldn't directly affect the brush import, but if the brush was far away from the origin I could see it leading into inaccuracies. If you copied the brush inside Hammer, then it probably wasn't in the same position, which is probably why the fresh vmf imported fine.

Can you look up the id of one of the inaccurate brushes (it's the number at the end of the object name in Blender), open the .vmf file in notepad, use CTRL+F to search for the id to find the inaccurate solid definition and send the definition here?

The solid definition should look something like this (the id here is `1231`):
```
	solid
	{
		"id" "1231"
		side
		{
			"id" "1232"
			"plane" "(-1748 -1024.0039 96.998) (-1773 -1052.002 80.998) (-1725.9985 -1059.0022 80.998)"
			"smoothing_groups" "0"
			"material" "tools/toolsclip"
			"uaxis" "[-0.9972 0 -0.0749 0] 0.25"
			"vaxis" "[0.0337 -0.8934 -0.4481 0] 0.25"
			"lightmapscale" "16"
		}
		side
		{
			"id" "1233"
			"plane" "(-1726.0039 -1059 113.0039) (-1772.9961 -1052.001 81) (-1772.9961 -1052.001 113.0051)"
			"smoothing_groups" "0"
			"material" "tools/toolsclip"
			"uaxis" "[0.9891 -0.1473 0 0] 0.25"
			"vaxis" "[0 0 -1 0] 0.25"
			"lightmapscale" "16"
		}
		side
		{
			"id" "1234"
			"plane" "(-1773.0039 -1052 113.0078) (-1773.0039 -1052 80.998) (-1748.0016 -1023.9974 96.9995)"
			"smoothing_groups" "0"
			"material" "tools/toolsclip"
			"uaxis" "[-0.666 -0.7459 0 0] 0.25"
			"vaxis" "[0 -0 -1 0] 0.25"
			"lightmapscale" "16"
		}
		side
		{
			"id" "1235"
			"plane" "(-1748.002 -1023.9961 129.0078) (-1748.002 -1023.9961 97) (-1725.998 -1059.0039 80.998)"
			"smoothing_groups" "0"
			"material" "tools/toolsclip"
			"uaxis" "[-0.5322 0.8466 0 0] 0.25"
			"vaxis" "[0 0 -1 0] 0.25"
			"lightmapscale" "16"
		}
		side
		{
			"id" "1236"
			"plane" "(-1726 -1059.002 113.0038) (-1773.0039 -1052.001 113.0038) (-1748.0012 -1023.998 129.0056)"
			"smoothing_groups" "0"
			"material" "tools/toolsclip"
			"uaxis" "[0.9972 -0 0.0749 0] 0.25"
			"vaxis" "[0.0337 -0.8934 -0.4481 0] 0.25"
			"lightmapscale" "16"
		}
	}
```

**Comment by dotrich** [comment]
Here is one of the same brushes shown in the OP. This particular brush is on-grid but is still affected by the inaccuracy. It is also within 2500-3000 units of world spawn. This brush is part of a func_detail made up of 36 brushes, which I intended to convert into a model.

Here is the brush in Blender:
https://user-images.githubusercontent.com/4912391/119237596-8ab96a00-bb35-11eb-8f01-5341535349bd.png

Here is the brush in Hammer:
https://user-images.githubusercontent.com/4912391/119238879-45009f80-bb3d-11eb-9efd-0d99ccce909e.png

	solid
	{
		"id" "7962878"
		side
		{
			"id" "604341"
			"plane" "(-296 2637 144) (-280 2637 144) (-288 2623 144)"
			"material" "PROPS/METALSTAINLESS01"
			"uaxis" "[0.866036 -0.49998 0 24.2837] 0.25"
			"vaxis" "[0.49998 0.866037 0 -95.6172] 0.25"
			"rotation" "0"
			"lightmapscale" "16"
			"smoothing_groups" "0"
		}
		side
		{
			"id" "604340"
			"plane" "(-280 2637 136) (-296 2637 136) (-288 2623 136)"
			"material" "PROPS/METALSTAINLESS01"
			"uaxis" "[0.866036 0.49998 0 -51.293] 0.25"
			"vaxis" "[0.49998 -0.866037 0 39.8623] 0.25"
			"rotation" "0"
			"lightmapscale" "16"
			"smoothing_groups" "0"
		}
		side
		{
			"id" "604339"
			"plane" "(-288 2623 144) (-280 2637 144) (-280 2637 136)"
			"material" "PROPS/METALSTAINLESS01"
			"uaxis" "[0.496139 0.868243 0 -20.5527] 0.25"
			"vaxis" "[0 0 -1 58] 0.25"
			"rotation" "0"
			"lightmapscale" "16"
			"smoothing_groups" "0"
		}
		side
		{
			"id" "604338"
			"plane" "(-296 2637 144) (-288 2623 144) (-288 2623 136)"
			"material" "PROPS/METALSTAINLESS01"
			"uaxis" "[-0.434428 0.748517 0.50099 -28.46] 0.25"
			"vaxis" "[-0.25148 0.433299 -0.865451 -73.3823] 0.25"
			"rotation" "0"
			"lightmapscale" "16"
			"smoothing_groups" "0"
		}
		side
		{
			"id" "604337"
			"plane" "(-280 2637 144) (-296 2637 144) (-296 2637 136)"
			"material" "DE_NUKE/NUKE_METALTRIMS_01"
			"uaxis" "[1 0 0 76.358] 0.5"
			"vaxis" "[0 0 -1 46] 0.5"
			"rotation" "0"
			"lightmapscale" "16"
			"smoothing_groups" "0"
		}
		editor
		{
			"color" "0 180 0"
			"visgroupshown" "1"
			"visgroupautoshown" "1"
		}
	}

**Comment by lasa01** [comment]
I think I fixed the issue. Can you test this?
[io_import_vmf.zip](https://github.com/lasa01/io_import_vmf/files/6534647/io_import_vmf.zip)

**Comment by dotrich** [comment]
I did a full import of brushes and props at 1 scale a few times and it seems to be fixed. Thanks!
https://user-images.githubusercontent.com/4912391/119420332-27c20180-bcf4-11eb-9264-a76691454c6e.png

I am a bit curious what was causing it.

**Comment by lasa01** [comment]
Seems like doing floating point calculations on the large coordinates was simply too inaccurate, "recentering" the coordinates to the solids before doing the calculations made the input coordinates much smaller, and the resulting vertex positions turned out much more accurate.
