### ISSUE TITLE
Blender freeze after load vmf on Manjaro Linux

### ISSUE THREAD

**Issue by Pollito001** [lasa01/io_import_vmf#84]
Blender complete freeze after load vmf on Manjaro Linux, Is this addon compatible with Linux?.

**Comment by lasa01** [comment]
This is probably a duplicate of #67.

I haven't properly tested the Linux support, it's experimental. Seems like probably Wine is freezing when decompiling certain models. If that's the case, then there's nothing I can do to fix it.
