### ISSUE TITLE
Support for MDL and VTF/VMT outside of VPK files

### ISSUE THREAD

**Issue by stopmotio** [lasa01/io_import_vmf#85]
**Is your feature request related to a problem? Please describe.**
When importing from certain games, such as The Stanley Parable, TF2, and portal, not everything is imported because of the many files outside of VPK archives

**Is your feature request related to a specific game? Please specify.**
Noticed when importing a TF2 map and having many objects missing

**Describe the solution you'd like**
I want this addon to be able to use folders as VPK files.

**Additional context**
None.

**Comment by lasa01** [comment]
There already is support for that. You might need to configure it yourself though, by adding a "Game directory" in the addon preferences. Currently the "Detect from game directory" button doesn't read gameinfo.txt so it might not detect every needed directory.
