### ISSUE TITLE
FileNotFoundError: VTFLib.dll

### ISSUE THREAD

**Issue by NewOkNo** [lasa01/io_import_vmf#95]
I am using this addon for the first time, downloaded everything needed, but got this output:

![blender_URZQd4FQOw](https://user-images.githubusercontent.com/72350904/133794992-9d609a79-b3a5-43b2-a0e3-cd4b002ae3ab.png)
 
![explorer_lzSMbYSSSv](https://user-images.githubusercontent.com/72350904/133795456-ccd704a6-c78d-403c-b378-b0ec059f11c4.png)

How can I fix it? Just download missing stuff or something else?

**Comment by lasa01** [comment]
You downloaded a Linux-only version. Please use 0.6.4 on Windows as
instructed in the download page.

**Comment by NewOkNo** [comment]
Oups, sry I'm blind xd
